# application.properties
spring.application.name=odds-calculator
spring.profiles.active=dev

server.port=8082

# External API
external.api.url=${EXTERNAL_API_URL:https://v3.football.api-sports.io}
external.api.key=${EXTERNAL_API_KEY:}

# Kafka producer
# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=odds-calculator
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/betlandia}
spring.datasource.username=${DB_USERNAME:betlandia}
spring.datasource.password=${DB_PASSWORD:betlandia}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Polling config
betlandia.ingestor.league-id=${LEAGUE_ID:1}
betlandia.ingestor.season=${SEASON:2026}
betlandia.ingestor.poll-interval-ms=${POLL_INTERVAL_MS:15000}
betlandia.ingestor.pre-match-poll-ms=${PRE_MATCH_POLL_MS:300000}